# Generated by Django 3.0.2 on 2020-07-01 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ifsc', models.CharField(blank=True, default='', max_length=128, null=True)),
                ('bank_id', models.CharField(blank=True, default='', max_length=128, null=True)),
                ('branch', models.CharField(blank=True, default='', max_length=128, null=True)),
                ('address', models.CharField(blank=True, default='', max_length=128, null=True)),
                ('city', models.CharField(blank=True, default='', max_length=128, null=True)),
                ('district', models.CharField(blank=True, default='', max_length=128, null=True)),
                ('state', models.CharField(blank=True, default='', max_length=128, null=True)),
                ('bank_name', models.CharField(blank=True, default='', max_length=128, null=True)),
            ],
        ),
    ]
