# Generated by Django 2.2.10 on 2020-07-01 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='address',
            field=models.CharField(blank=True, default='', max_length=800, null=True),
        ),
    ]
